post_tags:
  - id: audible_signal
    label: 音が鳴る信号機
  - id: non_audible_signal
    label: 音が鳴らない信号機
  - id: push_button_signal
    label: 押しボタン式信号機
  - id: crosswalk
    label: 横断歩道
  - id: misplaced_tactile_paving
    label: 配置が不適切な点字ブロック
  - id: deteriorated_tactile_paving
    label: 劣化した点字ブロック
  - id: obstructed_tactile_paving
    label: 物が置かれて通れない点字ブロック
  - id: footbridge_stairs_entry
    label: 歩道橋の階段の出入口
  - id: footbridge_elevator_entry
    label: 歩道橋のエレベーターの出入口
  - id: footbridge_ramp_entry
    label: 歩道橋のスロープの出入口